import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@components/components/Navbar";
import Header from "@components/components/Header";
import { supabase } from "@components/lib/supabaseClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TaeHyun Blog 관리자 콘솔",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = null;

  try {
    const {
      data: { session: fetchedSession },
      error,
    } = await supabase.auth.getSession();

    if (error) {
      console.error("Error fetching session:", error.message);
    } else {
      session = fetchedSession;
    }
  } catch (err) {
    console.error("Unexpected error:", err);
  }

  const isLoggedIn = !!session;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {!isLoggedIn ? (
          <div className="fixed top-[67px] left-0 w-[240px] h-[calc(100vh-67px)] p-container border-r border-slate-containerColor">
            <Navbar />
          </div>
        ): null}
        <main className={isLoggedIn ? "ml-[250px]" : ""}>{children}</main>
      </body>
    </html>
  );
}